### ISSUE TITLE
_ not defined

### ISSUE THREAD

**Issue by qamarhafeez** [cobbweb/jquery.scrollwatch#1]
I am having bug using jquery.scrollwatch
using jquery version

<script type="text/javascript" src="js/jquery-1.11.3.min.js"></script>

<script type="text/javascript" src="js/jquery-migrate-1.2.1.min.js"></script>

Please help

![bug](https://cloud.githubusercontent.com/assets/6185356/11354476/86032cd6-926d-11e5-8b7f-e1234db71035.PNG)

screenshots attached

**Comment by cobbweb** [comment]
Currently, jquery.scrollwatch also [depends on lodash](https://github.com/cobbweb/jquery.scrollwatch/blob/master/bower.json#L7). 

You'll need to add it to your page too for it to work.

**Comment by cobbweb** [comment]
Oooh, sorry just took another look at your screenshot and I see this isn't related to lodash. I'll take a better look.

**Comment by cobbweb** [comment]
Is that error actually coming from jquery.scrollwatch? I'm thinking it might be from a different jQuery plugin/library you're using.

**Comment by qamarhafeez** [comment]
sorry, i placed wrong screenshot file by mistake. It was on line number 10

_.bindAll(this, 'handleScroll', 'onScroll');

_ not defined

**Comment by qamarhafeez** [comment]
probably you are right. I did not include lodash in the page

**Comment by cobbweb** [comment]
Please let me know if adding lodash fixes the issue.

**Comment by cobbweb** [comment]
Closing with the assumption that adding lodash to page fixes the issue.
